preset: psr2

finder:
  exclude:
    - vendor
    - <%= dirBuild %>

enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_opening_tag
  - cast_spaces
  - combine_consecutive_unsets
<% if (projectPhpVersion >= 7.1) { -%>
  - compact_nullable_typehint
<% } -%>
  - concat_with_spaces
  - declare_equal_normalize
  - declare_strict_types
  - function_typehint_space
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
  - linebreak_after_opening_tag
  - lowercase_cast
  - method_separation
  - modernize_types_casting
  - native_function_casing
  - native_function_invocation
  - new_with_braces
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_spaces_outside_offset
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unreachable_default_argument_value
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - php_unit_construct
  - php_unit_dedicate_assert
  - phpdoc_add_missing_param_annotation
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_types
  - phpdoc_var_without_name
  - pow_to_exponentiation
  - random_api_migration
  - return_type_declaration
  - self_accessor
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - ternary_operator_spaces
  - ternary_to_null_coalescing
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unary_operator_spaces
  - whitespace_after_comma_in_array
