require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadJsonPath = ".vagrant/homestead.json"
homesteadYamlPath = ".vagrant/homestead.yml"
afterScriptPath = ".vagrant/after.sh"
aliasesPath = ".vagrant/aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    settings = nil
    if File.exists? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    elsif File.exists? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    end

    if (config.nil?) {
        config.hostsupdater.aliases = settings["hostaliases"].kind_of?(Array) ? settings["hostaliases"] : []

        Homestead.configure(config, settings)
    }

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath
    end
end
